#!/home/naw356/bin/python
import linecache
ppath = '/projects/b1027/Nick_work/PBE Potentials/'

with open('POSCAR', 'r') as poscar:
    lines = poscar.readlines()
    line = lines[5]
    
# VASP recommended pseudopotentials except for Eu, Yb
elem_dict = {
        'H' : 'H',
        'He': 'He',
        'Li': 'Li_sv',
        'Be': 'Be',
        'B' : 'B',
        'C' : 'C',
        'N' : 'N',
        'O' : 'O',
        'F' : 'F',
        'Ne': 'Ne',
        'Na': 'Na_pv',
        'Mg': 'Mg',
        'Al': 'Al',
        'Si': 'Si',
        'P' : 'P',
        'S' : 'S',
        'Cl': 'Cl',
        'Ar': 'Ar',
        'K' : 'K_sv',
        'Ca': 'Ca_sv',
        'Sc': 'Sc_sv',
        'Ti': 'Ti_sv',
        'V' : 'V_sv',
        'Cr': 'Cr_v',
        'Mn': 'Mn_pv',
        'Fe': 'Fe',
        'Co': 'Co',
        'Ni': 'Ni',
        'Cu': 'Cu',
        'Zn': 'Zn',
        'Ga': 'Ga_d',
        'Ge': 'Ge_d',
        'As': 'As',
        'Se': 'Se',
        'Br': 'Br',
        'Kr': 'Kr',
        'Rb': 'Rb_sv',
        'Sr': 'Sr_sv',
        'Y' : 'Y_sv',
        'Zr': 'Zr_sv',
        'Nb': 'Nb_sv',
        'Mo': 'Mo_sv',
        'Tc': 'Tc_pv',
        'Ru': 'Ru_pv',
        'Rh': 'Rh_pv',
        'Pd': 'Pd',
        'Ag': 'Ag',
        'Cd': 'Cd',
        'In': 'In_d',
        'Sn': 'Sn_d',
        'Sb': 'Sb',
        'Te': 'Te',
        'I' : 'I',
        'Xe': 'Xe',
        'Cs': 'Cs_sv',
        'Ba': 'Ba_sv',
        'La': 'La',
        'Ce': 'Ce',
        'Pr': 'Pr_3',
        'Nd': 'Nd_3',
        'Pm': 'Pm_3',
        'Sm': 'Sm_3',
        'Eu': 'Eu_3', 
        'Gd': 'Gd_3',
        'Tb': 'Tb_3',
        'Dy': 'Dy_3',
        'Ho': 'Ho_3',
        'Er': 'Er_3',
        'Tm': 'Tm_3',
        'Yb': 'Yb',
        'Lu': 'Lu_3',
        'Hf': 'Hf_pv',
        'Ta': 'Ta_pv',
        'W' : 'W_pv',
        'Re': 'Re',
        'Os': 'Os',
        'Ir': 'Ir',
        'Pt': 'Pt',
        'Au': 'Au',
        'Hg': 'Hg',
        'Tl': 'Tl_d',
        'Pb': 'Pb_d',
        'Bi': 'Bi_d',
        'Po': 'Po_d',
        'At': 'At_d',
        'Rn': 'Rn',
        'Fr': 'Fr_sv',
        'Ra': 'Ra_sv',
        'Ac': 'Ac',
        'Th': 'Th',
        'Pa': 'Pa',
        'U' : 'U',
        'Np': 'Np',
        'Pu': 'Pu',
        'Am': 'Am',
        'Cm': 'Cm'}

fo = open('POTCAR', 'w')
fo.close()
for elem in line.split():
    with open(ppath + elem_dict[elem] + '/POTCAR', 'r') as ep:
        elem_potcar = ep.readlines()
    with open('POTCAR', 'a') as f:
        elem_potcar = ''.join(elem_potcar)
        f.write(elem_potcar)
